### ISSUE TITLE
request param validation should accept lists of tuples

### ISSUE THREAD

**Issue by ewheeler** [davidhuser/dhis2.py#4]
Thanks for the lovely library!

I found a limitation that should be simple to fix.
Many DHIS2 API endpoints allow repeated parameters, but this library does not.

For example, table `1.29` in the `1.17.6. Reading data values` section of [DHIS2 API docs](https://docs.dhis2.org/2.26/en/developer/html/dhis2_developer_manual_full.html) describes several parameters that "Can be repeated any number of times." (such as `dataSet`, `orgUnit`, `period`, etc)

Luckily, the `requests` library supports repeated parameters if the caller provides as a list of tuples: http://docs.python-requests.org/en/latest/user/quickstart/#more-complicated-post-requests

However, the [_validate_request](https://github.com/davidhuser/dhis2.py/blob/master/dhis2/api.py#L169) method raises if `params` is not a `dict`

**Comment by davidhuser** [comment]
Valid point I have not thought about! It's [enabled](https://github.com/davidhuser/dhis2.py/blob/e4484f60cd2e31a5763f190d78b50b8e9d3673b1/dhis2/api.py#L169) on 1.5.0 in commit https://github.com/davidhuser/dhis2.py/commit/e4484f60cd2e31a5763f190d78b50b8e9d3673b1.
Thanks!

**Comment by davidhuser** [comment]
docs example here: https://github.com/davidhuser/dhis2.py#multiple-params

**Comment by ewheeler** [comment]
@davidhuser thanks for the quick fix!! much appreciated!!
