### ISSUE TITLE
api.delete does not allow payload

### ISSUE THREAD

**Issue by plinnegan** [davidhuser/dhis2.py#9]
### Description
Cannot remove dataElements from dataElementGroups as in [DHIS2 dev guide](https://docs.dhis2.org/2.29/en/developer/dhis2_developer_manual.pdf), section:
**1.9.4.2. Adding or removing multiple objects**
Here you are required to DELETE with a payload of the dataElements in the group you wish to remove.
Attempting a DELETE with payload parameter of either `json=` or `data=` fails as this is not supported currently in dhis2.py.
Could you please add this feature in the next release?

Many thanks,
Pete

**Comment by davidhuser** [comment]
resolved in version 1.8.0 and PR https://github.com/davidhuser/dhis2.py/pull/10
